version: "3"

services:

  app:
    build: php
    container_name: app
    ports:
      - "9000"
    volumes:
      - ../.:/var/www
      - ./php/log:/var/log:rw,cached
    networks:
      - app-network

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ../.:/var/www
      - ./nginx/log:/var/log/nginx:rw,cached
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data:rw,cached
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
