version: "3"

services:

  app:
    build: php
    container_name: app
    ports:
      - "9000"
    volumes:
      - ../.:/var/www
      - ./php/log:/var/log:rw,cached
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ../.:/var/www
      - ./nginx/log:/var/log/nginx:rw,cached
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/dumps:/dumps:rw,cached
      - ./database/data:/var/lib/mysql:rw,cached
      - ./database/config:/etc/mysql/conf.d:rw,cached
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    tty: true
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data:rw,cached
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
